extends: airbnb
parser: babel-eslint
env:
  browser: true
  node: true
  es6: true
  mocha: true
  jest: true
plugins:
  - react
  - import
  - react-hooks
rules:
  linebreak-style: 0
  no-console: 0
  arrow-parens: 0
  implicit-arrow-linebreak: 0
  operator-linebreak: 0
  no-confusing-arrow: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/extensions: 0
  jsx-a11y/no-static-element-interactions: 0
  jsx-a11y/anchor-is-valid: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-filename-extension: 0
  react/forbid-prop-types: 0
  react/require-default-props: 0
  react/jsx-wrap-multilines: 2
  react-hooks/rules-of-hooks: "error"
